# Generated by Django 4.2.3 on 2023-07-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_series"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Series",
        ),
    ]
